spring:

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: password
      jdbc-url: jdbc:mysql://localhost:3306/JIHAOSHI?useUnicode=yes&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Taipei
      pool-name: jdbc/jihaoshi2